### ISSUE TITLE
keepalive not working if only timeoutMs is set in options

### ISSUE THREAD

**Issue by frankville** [mquander/minijanus.js#1]
Hi, I've been getting no such session (id) errors when using minijanus to control mi janus instance. Correct me if I'm wrong but it seems that if someone forgets to set both timeout and keepalive values  when passing the options to minijanus (like me that I was setting only timeoutMs)  then the timeout and/or the keepalive functionality  will not work. The solution I think would be to check not only if the options parameter is defined but also every property in the object. Hope it helps.

**Comment by mqp** [comment]
Seems like a great suggestion, so I fixed it. See #2. Thanks!

**Comment by frankville** [comment]
Great! You're welcome. Thank you for the fix.
