### ISSUE TITLE
The "hint" attribute is not reliable in determining if the request will be responded to asynchronously

### ISSUE THREAD

**Issue by michaelfranzl** [mquander/minijanus.js#3]
https://github.com/mozilla/minijanus.js/blob/a93018cc894319fa61a6113945e0301bf4d28e08/minijanus.js#L108

This is just a heads-up that the presence of the "hint" attribute depends on the server-side plugin implementation. If "hint" is not present in a synchronous response to a request, the asynchronous response will not resolve the corresponding Promise.

**Comment by mqp** [comment]
Ah, thanks for the heads-up. I didn't realize that when I wrote this. I will fix this up to be really correct.
